### ISSUE TITLE
Encode plugin not working with server option

### ISSUE THREAD

**Issue by bilalmalkoc** [pqina/filepond-plugin-file-encode#18]
**Describe the bug**
getFileEncodeBase64String method returns an error when using server option in FilePond. If i remove server option, everthing works fine.

**To Reproduce**

1. Go to https://stackblitz.com/edit/js-uzqmrn?file=index.js
2. Click on **Crate Uploder** button.
3. Look console.
4. See error.

**Comment by rikschennink** [comment]
Why do you want to use file encoding and the server property at the same time?.

**Comment by bilalmalkoc** [comment]
Because i am editing images with [TUI](https://github.com/nhn/tui.image-editor). So i need to access encoded image string for edit image.

**Comment by rikschennink** [comment]
In that situation I advise not loading the file-encode plugin as it is intended for uploading files as base64 strings. 

Better to get the file object and then convert it to base64 manually before sending it to TUI. See article below on how to convert files to base64. 

https://pqina.nl/blog/convert-a-file-to-a-base64-string-with-javascript/

Obviously I'd love to know whyyou went with TUI instead of Doka Image Editor, is there any feature you're missing?

**Comment by bilalmalkoc** [comment]
OK. I will use manual way to get encoded string. Thanks.

Doka is better but, i am using image editor in my commercial product. And Doka's license price is equal with my yearly sales.

**Comment by rikschennink** [comment]
Thanks for the insight @bilalmalkoc, and good luck with your product!

I'll close the issue.
